background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 4
    contrast = 1.10
    brightness = 1.02
    vibrancy = 0.5
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +'%H:%M')</b>"
    color = rgba(255, 255, 255, 0.95)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    shadow_passes = 3
    shadow_size = 8
    position = 0, 130
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(LC_TIME=C date +'%A %d %B %Y')"
    color = rgba(255, 255, 255, 0.8)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    shadow_passes = 1
    position = 0, 45
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(255, 255, 255, 0.5)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false

    check_color = rgba(0, 255, 200, 0.8)
    fail_color = rgba(255, 80, 80, 0.8)

    placeholder_text = <span foreground="##ffffffaa"><i>Password...</i></span>

    position = 0, -60
    halign = center
    valign = center
}

shape {
    monitor =
    size = 280, 140
    color = rgba(255, 255, 255, 0.08)
    border_size = 2
    border_color = rgba(255, 255, 255, 0.35)
    rounding = 16
    shadow_passes = 2
    position = 60, -60
    halign = left
    valign = center
}

label {
    monitor =
    text = cmd[update:2000] echo "<b>SYSTEM MONITOR</b><br/> CPU: $(top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}')%<br/> RAM: $(free -m | awk '/Mem:/ { printf("%.1fGB / %.1fGB", $3/1024, $2/1024) }')<br/>󰋊 DISK /: $(df -h / | awk 'NR==2 {print $3 " / " $2 " (" $5 ")"}')"
    color = rgba(255, 255, 255, 0.9)
    font_size = 13
    font_family = JetBrainsMono Nerd Font
    position = 80, -60
    halign = left
    valign = center
}

shape {
    monitor =
    size = 320, 140
    color = rgba(255, 255, 255, 0.08)
    border_size = 2
    border_color = rgba(255, 255, 255, 0.35)
    rounding = 16
    shadow_passes = 2
    position = -60, -60
    halign = right
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/now_playing.sh
    color = rgba(255, 255, 255, 0.95)
    font_size = 13
    font_family = JetBrainsMono Nerd Font
    position = -80, -40
    halign = right
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(playerctl status 2>/dev/null | grep -q 'Playing' && echo '󰏤 Playing' || echo '󰐊 Paused')"
    color = rgba(0, 230, 255, 0.85)
    font_size = 11
    font_family = JetBrainsMono Nerd Font
    position = -80, -85
    halign = right
    valign = center
}